// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: protos/edge/risk/v1/service.proto

package v1

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	data "github.com/xefino/quantum-cli-go/data"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RiskManagementService_GetName_FullMethodName     = "/protos.edge.risk.v1.RiskManagementService/GetName"
	RiskManagementService_ModifyOrder_FullMethodName = "/protos.edge.risk.v1.RiskManagementService/ModifyOrder"
)

// RiskManagementServiceClient is the client API for RiskManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskManagementServiceClient interface {
	// GetName retrieves an identifier associated with the service, allowing the strategy runner to
	// uniquely identify it when multiple filter services are being referenced. It will return a
	// name result showing the address, ID and human-readable name of the filter service that processed
	// the original request.
	GetName(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*data.NameResult, error)
	// ModifyOrder takes an existing order and modifies it to hedge against known risk. This endpoint
	// will be responsible for assigning stop-losses, take-profits, and limits as necessary. This is
	// done by taking the trade object from the ModifyOrderRequest object, making the necessary modifications,
	// and setting the associated field on the ModifyOrderResult object.
	ModifyOrder(ctx context.Context, in *ModifyOrderRequest, opts ...grpc.CallOption) (*ModifyOrderResult, error)
}

type riskManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskManagementServiceClient(cc grpc.ClientConnInterface) RiskManagementServiceClient {
	return &riskManagementServiceClient{cc}
}

func (c *riskManagementServiceClient) GetName(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*data.NameResult, error) {
	out := new(data.NameResult)
	err := c.cc.Invoke(ctx, RiskManagementService_GetName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskManagementServiceClient) ModifyOrder(ctx context.Context, in *ModifyOrderRequest, opts ...grpc.CallOption) (*ModifyOrderResult, error) {
	out := new(ModifyOrderResult)
	err := c.cc.Invoke(ctx, RiskManagementService_ModifyOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskManagementServiceServer is the server API for RiskManagementService service.
// All implementations must embed UnimplementedRiskManagementServiceServer
// for forward compatibility
type RiskManagementServiceServer interface {
	// GetName retrieves an identifier associated with the service, allowing the strategy runner to
	// uniquely identify it when multiple filter services are being referenced. It will return a
	// name result showing the address, ID and human-readable name of the filter service that processed
	// the original request.
	GetName(context.Context, *empty.Empty) (*data.NameResult, error)
	// ModifyOrder takes an existing order and modifies it to hedge against known risk. This endpoint
	// will be responsible for assigning stop-losses, take-profits, and limits as necessary. This is
	// done by taking the trade object from the ModifyOrderRequest object, making the necessary modifications,
	// and setting the associated field on the ModifyOrderResult object.
	ModifyOrder(context.Context, *ModifyOrderRequest) (*ModifyOrderResult, error)
	mustEmbedUnimplementedRiskManagementServiceServer()
}

// UnimplementedRiskManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRiskManagementServiceServer struct {
}

func (UnimplementedRiskManagementServiceServer) GetName(context.Context, *empty.Empty) (*data.NameResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetName not implemented")
}
func (UnimplementedRiskManagementServiceServer) ModifyOrder(context.Context, *ModifyOrderRequest) (*ModifyOrderResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyOrder not implemented")
}
func (UnimplementedRiskManagementServiceServer) mustEmbedUnimplementedRiskManagementServiceServer() {}

// UnsafeRiskManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskManagementServiceServer will
// result in compilation errors.
type UnsafeRiskManagementServiceServer interface {
	mustEmbedUnimplementedRiskManagementServiceServer()
}

func RegisterRiskManagementServiceServer(s grpc.ServiceRegistrar, srv RiskManagementServiceServer) {
	s.RegisterService(&RiskManagementService_ServiceDesc, srv)
}

func _RiskManagementService_GetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskManagementServiceServer).GetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskManagementService_GetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskManagementServiceServer).GetName(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskManagementService_ModifyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskManagementServiceServer).ModifyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskManagementService_ModifyOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskManagementServiceServer).ModifyOrder(ctx, req.(*ModifyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskManagementService_ServiceDesc is the grpc.ServiceDesc for RiskManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.edge.risk.v1.RiskManagementService",
	HandlerType: (*RiskManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetName",
			Handler:    _RiskManagementService_GetName_Handler,
		},
		{
			MethodName: "ModifyOrder",
			Handler:    _RiskManagementService_ModifyOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/edge/risk/v1/service.proto",
}
